version: 0.2

phases:
  install:
    commands:
      - echo Nothing to install, container image should have it all based on what we selected
  pre_build:
    commands:
      - echo Just listing basic information about the environment
      - which mvn
      - mvn -version
      - pwd
      - REPOSITORY_URI=535243943550.dkr.ecr.us-east-2.amazonaws.com/park
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - mvn package
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Working on creating the tar ball with the WAR and AppSpec file for CodeDeploy
      - mkdir appfiles
      - cd appfiles
      - cp ../target/managemylearning-user-portal-0.0.1-SNAPSHOT.jar mmluserportal.jar
      - cp ../runUserPorta.sh runUserPortal.sh      
      - ls -al
      - tar -zcvf ../target/MMLUserPortal.tar.gz *.*
      - cp ../Dockerfile .  
      - echo Building the Docker image...          
      - docker build -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
      - echo Build completed on `date`
artifacts:
  files:
    - appfiles/mmluserportal.jar
    - appfiles/runUserPortal.sh
  discard-paths: yes
